### ISSUE TITLE
User can send an empty form

### ISSUE THREAD

**Issue by mihaela-i** [mirceageorgescu/hop-hooligans#2]
The user is able to submit an empty form on the Contact page by directly clicking on Send Message. http://hop-hooligans.netlify.com/contact

#newbie

**Comment by mihaela-i** [comment]
Partially fixed, can still send form with only spaces for Name and message body.

**Comment by mihaela-i** [comment]
....i have no idea how to reassign this 😓

**Comment by mirceageorgescu** [comment]
Valid. As. Fuck.

But... still... 

Not going to fix it because #nobodydoesthat.

**Comment by mihaela-i** [comment]
Pfff... except spammers. At least add a Captcha.

**Comment by mirceageorgescu** [comment]
Nah, spammers send spam, not empty characters.

And I hate captcha. So bad.

Against spammers we're using a technique that involves a honeypot. We have a field visually hidden called last-name. If there's content in that field when submitting we know for sure it's spam and discard it.

**Comment by mirceageorgescu** [comment]
Lame attempt to assign to mykey2005 by replying this email.

**Comment by mihaela-i** [comment]
Fine, fine, it's your vulnerable website 😷
